### ISSUE TITLE
TL866 native bootloader support

### ISSUE THREAD

**Issue by JohnDMcMaster** [ProgHQ/open-tl866#1]
Highly desirable to support the original update mechanism so 1) don't need external programmer 2) can go back to original firmware if need be.

This probably involves messing with linker scripts to get code offset past the first page (which has the bootloader). Also need to investigate how to properly apply the encryption table

**Comment by JohnDMcMaster** [comment]
I wasn't aware these are full dumps: https://github.com/radiomanV/TL866/tree/master/TL866_Updater/C%23/firmware

So should be able to flash back if need be

**Comment by Elemecca** [comment]
I've been working on this for the last week or so. You can track my progress over at my repo:
https://github.com/Elemecca/open-tl866/tree/t-bootloader

So far I've implemented a client for the stock bootloader in Python that can flash Intel Hex files or the stock `update.dat`, set up the open firmware build to be compatible with the bootloader, and started implementing a stub of the stock USB protocol in the open firmware so that the official client can reset into the bootloader and flash the stock firmware. I'm still working on getting reset to bootloader to work properly, and then I need to update the documentation.

As my branch stands the open firmware can be flashed via the stock bootloader and it works OK, but to get back into the bootloader you have to short pin RC1 to Vcc.

**Comment by JohnDMcMaster** [comment]
This is great! Thanks for contributing! I'll try to look at your WIP in the near future. Please let me know if you need anything to help move this forward.

FYI there is also a freenode IRC channel #proghq
